version: "3.8"

services:
  catalogdb:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: Services/Catalog/Catalog.Api
      dockerfile: Dockerfile

volumes:
  mongo_data:
